# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArchForge < Formula
  desc "Generate Go project structures based on proven architectural patterns"
  homepage "https://github.com/arch-forge/cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arch-forge/cli/releases/download/v1.0.0/cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "8355d49e760fab1bbef87b653295cd3f2d451331c2f1d6c35579ce030c5fe2ac"

      define_method(:install) do
        bin.install "arch_forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arch-forge/cli/releases/download/v1.0.0/cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "a99775cfd2ed7cc6feeaed8cf500aed0b624f3e71296d41ff1d36037c8302a22"

      define_method(:install) do
        bin.install "arch_forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arch-forge/cli/releases/download/v1.0.0/cli_1.0.0_linux_amd64.tar.gz"
      sha256 "9e2ebd2636b8bc28ccb195cf83e1bde1778f124336e6616521a63c0eabadb4c1"
      define_method(:install) do
        bin.install "arch_forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arch-forge/cli/releases/download/v1.0.0/cli_1.0.0_linux_arm64.tar.gz"
      sha256 "e67b524da4c6dd379a3f11e21245160b870e8226f49a13d2e30f04ee358ff702"
      define_method(:install) do
        bin.install "arch_forge"
      end
    end
  end

  test do
    system "#{bin}/arch_forge", "--version"
  end
end
