# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArchForge < Formula
  desc "Generate Go project structures based on proven architectural patterns"
  homepage "https://github.com/arch-forge/cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arch-forge/cli/releases/download/v1.0.0/cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "829fa8764ec2379f7974a750b086b222eabf9d29e26c3771ae4f3b49a21a8762"

      define_method(:install) do
        bin.install "arch_forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arch-forge/cli/releases/download/v1.0.0/cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "b9175c1e9812526657ce7cc60007a7e3871b874200ea273eb3032a085896e93f"

      define_method(:install) do
        bin.install "arch_forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arch-forge/cli/releases/download/v1.0.0/cli_1.0.0_linux_amd64.tar.gz"
      sha256 "f5407383c9d722cbf8279cab2b2850e9b0025229e1d83d8f4203e775c9062dbe"
      define_method(:install) do
        bin.install "arch_forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arch-forge/cli/releases/download/v1.0.0/cli_1.0.0_linux_arm64.tar.gz"
      sha256 "041ff5f3329b24970007d4b7348f6e13ac27e9078aef9dce27e86c4a192a2297"
      define_method(:install) do
        bin.install "arch_forge"
      end
    end
  end

  test do
    system "#{bin}/arch_forge", "--version"
  end
end
